### PR TITLE
Revert to using the english dictionary

### PR DESCRIPTION
**Pull request by corporealshift**
Turns out that we should have been using `english` the whole time and the mistake was a config that is set to simple. This needs to be english and we will fix the config on the other side of things

### CODE REVIEW

**Review by KaraFox — APPROVED** [review]

**Comment by jahndis** [comment]
How are you generating the dist? It really shouldn't be generating this much each time.

**Comment by corporealshift** [comment]
> How are you generating the dist? It really shouldn't be generating this much each time.

uh i did the thing it says in the readme

**Comment by jahndis** [comment]
> > How are you generating the dist? It really shouldn't be generating this much each time.
> 
> uh i did the thing it says in the readme

Maybe try `yarn clean && yarn build` instead of npm? We should probably take out the `npm` part of those scripts.

**Comment by corporealshift** [comment]
> > > How are you generating the dist? It really shouldn't be generating this much each time.
> > 
> > 
> > uh i did the thing it says in the readme
> 
> Maybe try `yarn clean && yarn build` instead of npm? We should probably take out the `npm` part of those scripts.

I tried that in a separate branch and I have the same number of files changed

**Review by jahndis — APPROVED** [review]

**Review by KaraFox — APPROVED** [review]

**Pull request merged**
